server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/edgarramones/config-data.git
          searchPaths: config-data
          username: edgarramones
          password: Administrador1977
          default-label: "master"
  security:
    user:
      name: edgarramones
      password: Administrador1977  