server:
  port: 8889
spring:
  application:
    name: CONFIG-SERVICE
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


  #server:
  #port: 8081
  spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
        git:
          uri: https://github.com/edgarramones/config-data
          searchPaths: config-data
          username: admin
          password: admin
          default-label: "master" 
                  


